### ISSUE TITLE
Generated classes are not filtered

### ISSUE THREAD

**Issue by alexzaitsev** [alexzaitsev/apk-dependency-graph#1]

**Comment by reisub** [comment]
This is the only thing stopping this tool from being useful for me.
I've looked at the generated classes in my projects and figured out how to filter them:
1. Dagger 2 (not sure about Dagger 1) generated classes are annotated with `@Generated`
2. ButterKnife generated classes end in `_ViewBinding`

The main problem is Dagger since it binds together a bunch of classes and then it looks like a big forest of classes.

**Comment by alexzaitsev** [comment]
It's implemented in 0.0.5 with `Live editor` feature. How-to: https://github.com/alexzaitsev/apk-dependency-graph/wiki
