### ISSUE TITLE
Error: Unable to access jarfile

### ISSUE THREAD

**Issue by dGorod** [alexzaitsev/apk-dependency-graph#13]
Hello!
I downloaded last release. Trying to run bat (OS is Windows 10).
And have next error:

> Error: Unable to access jarfile C:\Users\dGorod\Android

Maybe because my Android SDK installed not by default path?

**Comment by alexzaitsev** [comment]
Hello, @dGorod, have you resolved this issue? If no - please show detailed logs from your command line / terminal.

**Comment by dGorod** [comment]
This is all logs that I got. And no, I did not investigate further. As the way to my APK file I used absolute path, like: 

> "C:\Users\dGorod\Android Studio Projects\ [project folder] \app\build\outputs\apk\build-v16-debug.apk"

**Comment by alexzaitsev** [comment]
correct
it's pointed in the readme that you should use absolute paths, for instance  
`run.bat full\path\to\the\apk\app-release.apk com.example.test`

**Comment by arenshaee** [comment]
it's because of the path of jar file. for my case, my path includes space, so open run.bat file with editor, and at line 27, where java execution commands are:
`java -jar %~dp0\build\libs\apk-dependency-graph.jar -i %outPath% -o %jsonPath% -a %1 -f %2`

and then add quotes around all paths like below:

`java -jar "%~dp0\build\libs\apk-dependency-graph.jar" -i "%outPath%" -o "%jsonPath%" -a %1 -f %2`
