### ISSUE TITLE
Empty list of dependencies

### ISSUE THREAD

**Issue by venvear** [alexzaitsev/apk-dependency-graph#26]
Hello.
I'm trying to build a graph for my app, but I get an empty dependency array.

var dependencies = {links:[
]};

P.S. I'm use apktool 2.3.0.

**Comment by matthew-carroll** [comment]
I'm having the same issue.  I've tried using release 0.1.2 and 0.1.1.  Both give me an error during execution but finish executing anyway.  When I open the index.html file there is no graph (but the controls are there).  The JS dependencies file is empty as @venvear mentioned.

I'm running the release shell script on OSX 10.12.6 (Sierra)

NPE:
...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:58)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:516)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
	at brut.apktool.Main.cmdDecode(Main.java:163)
	at brut.apktool.Main.main(Main.java:81)
Success! Now open index.html in your browser.

**Comment by alexzaitsev** [comment]
Guys, as you see, there is an exception in 3rd-party library so I cannot fix it. I'll leave this issue opened for future investigations.

**Comment by matthew-carroll** [comment]
So is this an issue with a known work around?  Or is your project no longer functional?

**Comment by alexzaitsev** [comment]
I cannot assume that it's not functional based on reviews of only two people. Of course I'll recheck it by myself using apktool 2.3.0.

**Comment by alexzaitsev** [comment]
I checked it and as expected it works ok. I've made a new [release](https://github.com/alexzaitsev/apk-dependency-graph/releases/tag/0.1.3) with apktool 2.3.0.  
Again, you have this issue because `apktool` cannot decompile your certain apk because of some internal issue. You may try to fix the issue in `apktool` by yourself, rebuild, and include this new version instead of current one or try `apk-dependency-graph` of the version [0.1.2](https://github.com/alexzaitsev/apk-dependency-graph/releases/tag/0.1.2).  
That's all that I can suggest you for now.

**Comment by alexzaitsev** [comment]
Closed unintentionally, I'll leave it open for now.

**Comment by alexzaitsev** [comment]
I guess it can be closed. Feel free to reopen.
