### ISSUE TITLE
Can't analyze with nofilter

### ISSUE THREAD

**Issue by SupinePandora43** [alexzaitsev/apk-dependency-graph#46]
if i run without filter (`nofilter`)
i'll get `Check your filter` after decompiling dex file

**Comment by alexzaitsev** [comment]
Yes that's correct behavior. For now lets leave is as it is because @victorrattis works on the https://github.com/alexzaitsev/apk-dependency-graph/issues/40 and the app will be desktop soon.

P.S. There is an example of using `nofilter` [here](https://github.com/alexzaitsev/apk-dependency-graph#usage).

**Comment by alexzaitsev** [comment]
Fixed in scope of #48
